#! /bin/bash
clear
function Menu() { 
echo -e  "1. Create user\n2. Delete user\n3. Create group\n4. Delete group\n5. Edite user\n6. Show info\n0. Exit"
read choice
}
function Menu1(){
echo -e "1. NewGroupName\n2. ModGroup\n0. Exit"
read ChoiseGroup
}
#########################################################################################
function CreateUser () {
clear
echo -e "1) Name\n2) Name + UID +GID"
read userChoice




	if  (($userChoice== 1 ))
	then
	echo "Enter username: "
	read newUserName
	useradd $newUserName
		if (($?==0))
		then echo "User create, choose passwd!"
	passwd $newUserName
	else 
		clear
		echo "Sorry, this User not free, choose something else"
		cat /etc/passwd | grep $newUserName
	fi





elif (( $userChoice == 2))
then 
	echo "User + UID + GID"
	read group2
	groupadd $group2
	read newUserName2
	useradd $newUserName2
	usermod $newUserName2 --gid $group 
fi	
}
###############################################################################
function AddGroup () {
echo "NewGroup Name"
read AddGroup
groupadd $AddGroup
if (($?==0))
 then echo "Group create"
else echo "choose other groupname"
fi
}
function ModGroup() {
echo "Whot name of group you wont to mod?"
read ModGroup
echo "New Name"
read NewGroup
groupmod $ModGroup -n $NewGroup
	if (($?==0))
	then echo "saccess rename"
	else echo "problem"
	fi

}
################################################################################
function ChoiseGroup (){
exit=true
while [ $exit==true ]
do
Menu1;
case $ChoiseGroup in
			1)AddGroup; ;;
			2)ModGroup; ;;
			0)let exit=false; ;;
			*)echo "R.T.F.M."; ;;
esac
done




 
}
###########################################################################
function DeleteUser() {
echo "Delete User"
read userDelete
userdel $userDelete
}
exit=true

while [ $exit==true ]
do
Menu;
case $choice in
	1)CreateUser; ;;
	2)DeleteUser; ;;
	3)ChoiseGroup; ;;
	0)echo "Bye!"; let exit=false; ;;
	*)echo "R.T.F.M."; ;;
esac
done
